const $=id=>document.getElementById(id);const symbols={GBP:'£',USD:'$',EUR:'€'};let nextId=1;
const fields={business:$('business'),number:$('number'),date:$('date'),client:$('client'),currency:$('currency')};
function money(n){return `${symbols[fields.currency.value]||'£'}${(Number(n)||0).toFixed(2)}`}
function esc(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function itemRow(item){const tr=document.createElement('tr');tr.dataset.id=item.id;tr.innerHTML=`<td><input data-f="description" value="${esc(item.description)}"></td><td><input data-f="qty" type="number" min="0" step=".01" value="${item.qty}"></td><td><input data-f="unit" value="${esc(item.unit)}"></td><td><input data-f="price" type="number" min="0" step=".01" value="${item.price}"></td><td class="line-total">${money(item.qty*item.price)}</td><td><button class="delete" type="button">Delete</button></td>`;tr.querySelectorAll('input').forEach(i=>i.addEventListener('input',refresh));tr.querySelector('.delete').onclick=()=>{tr.remove();refresh()};return tr}
function rows(){return [...$('items').querySelectorAll('tr')].map(tr=>{const get=f=>tr.querySelector(`[data-f="${f}"]`).value;const x={description:get('description'),qty:+get('qty')||0,unit:get('unit'),price:+get('price')||0};x.total=x.qty*x.price;return x})}
function refresh(){const data=rows();const total=data.reduce((s,x)=>s+x.total,0);data.forEach((x,i)=>$('items').rows[i].querySelector('.line-total').textContent=money(x.total));$('subtotal').textContent=money(total);$('grandTotal').textContent=money(total);renderPreview(data,total)}
function renderPreview(data,total){const date=fields.date.value||new Date().toISOString().slice(0,10);$('preview').innerHTML=`<div class="preview-head"><div><h3>${esc(fields.business.value||'Business name')}</h3><span>Professional trade services</span></div><div class="meta"><span><b>Quote #</b> ${esc(fields.number.value||'N/A')}</span><span><b>Date</b> ${esc(date)}</span><span><b>Currency</b> ${fields.currency.value}</span></div></div><div class="client"><div><b>Client</b><br>${esc(fields.client.value||'Client name')}</div><div><b>Prepared by</b><br>${esc(fields.business.value||'Business name')}</div></div><table><thead><tr><th>Description</th><th>Qty</th><th>Unit</th><th>Unit price</th><th>Total</th></tr></thead><tbody>${data.length?data.map(x=>`<tr><td>${esc(x.description)}</td><td>${x.qty}</td><td>${esc(x.unit)}</td><td>${money(x.price)}</td><td>${money(x.total)}</td></tr>`).join(''):'<tr><td colspan="5">No items yet.</td></tr>'}</tbody></table><div class="summary"><div>Subtotal <span>${money(total)}</span></div><div class="grand">Grand total <span>${money(total)}</span></div></div>`}
function add(item={description:'New item',qty:1,unit:'unit',price:0}){$('items').appendChild(itemRow({...item,id:nextId++}));refresh()}
function parse(text){const chunks=text.split(/[,.;]|\band\b|\bplus\b/i).map(x=>x.trim()).filter(Boolean);const result=[];const patterns=[[/([0-9]+(?:\.[0-9]+)?)\s*(?:of\s+)?(.+)/i,'unit']];chunks.forEach(chunk=>{const m=chunk.match(patterns[0][0]);let qty=m?+m[1]:1;let d=(m?m[2]:chunk).replace(/^(install|replace|run|fit|repair|service|supply)\s+/i,'').trim();let unit='unit',price=120;if(/fuse box/i.test(d)){unit='fuse box';price=250}else if(/socket/i.test(d)){unit='socket';price=65}else if(/cable|wire/i.test(d)){unit='m';price=35}else if(/switch/i.test(d)){unit='switch';price=45}else if(/\b(m|metres?|meters?)\b/i.test(d)){unit='m';price=35}d=d.replace(/\b(m|metres?|meters?)\b/gi,'').trim();if(d)result.push({description:d,qty,unit,price})});return result.length?result:[{description:text.trim(),qty:1,unit:'job',price:150}]}
$('generate').onclick=()=>{const text=$('job').value.trim();if(!text){alert('Please describe the job first.');return}$('items').innerHTML='';parse(text).forEach(add);$('start').classList.add('hidden');$('workspace').classList.remove('hidden');if(!$('date').value)$('date').value=new Date().toISOString().slice(0,10);refresh()};$('add').onclick=()=>add();$('print').onclick=()=>window.print();$('newQuote').onclick=()=>{ $('workspace').classList.add('hidden');$('start').classList.remove('hidden');$('job').value=''};Object.values(fields).forEach(f=>{f.addEventListener('input',refresh);f.addEventListener('change',refresh)});$('job').addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter')$('generate').click()});
